version: '3'

services:
  nodejs:
    container_name: nodejs
    image: node:alpine
    env_file: .env
    ports:
      - 64999:3000
    command: npm start
    working_dir: /usr/src/app
    volumes:
      - ./service:/usr/src/app/
    networks:
      - docketu

networks:
  docketu:
    driver: bridge
